# Generated by Django 3.2 on 2022-01-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220107_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('JM', 'Junior Male'), ('JF', 'Junior Female')], max_length=2, null=True),
        ),
    ]
