# Generated by Django 3.2 on 2022-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220113_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_length',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='length',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
