# Generated by Django 3.2 on 2022-01-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220113_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_length',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='length',
        ),
    ]
