# Generated by Django 3.2 on 2022-01-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220113_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Junior Male'), ('4', 'Junior Female')], max_length=2, null=True),
        ),
    ]
