# Generated by Django 3.2 on 2022-01-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220118_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={},
        ),
        migrations.AddConstraint(
            model_name='productcolour',
            constraint=models.UniqueConstraint(fields=('product', 'colour'), name='product_colour_constraint'),
        ),
        migrations.AddConstraint(
            model_name='productinventory',
            constraint=models.UniqueConstraint(fields=('product', 'product_colour', 'size'), name='product_inventory_constraint'),
        ),
    ]
